# Generated by Django 2.0.1 on 2018-01-13 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(blank=True, help_text='Загрузите картинку', upload_to='preview_images/%Y/%m/%d', verbose_name='Превью-Картинка')),
                ('header', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Адрес сайта')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('category', models.CharField(blank=True, choices=[('SITE', 'Сайт'), ('GAME', 'Игра'), ('SOFT', 'Софт')], default='SITE', max_length=30, verbose_name='Категория')),
            ],
        ),
    ]
