# Generated by Django 2.0.1 on 2018-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='slug_header',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='elements',
            name='category',
            field=models.CharField(blank=True, choices=[('sites', 'Сайты'), ('games', 'Игры'), ('software', 'Софт')], default='sites', max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='preview_images/%Y/%m/%d', verbose_name='Превью-Картинка'),
        ),
    ]
