# Generated by Django 2.0.1 on 2018-01-18 22:30

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180116_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображения', upload_to=gallery.models.get_image_path, verbose_name='Галерея проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Elements')),
            ],
        ),
    ]
