# Generated by Django 2.0.1 on 2018-02-02 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_screenshot', models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='Gallery/Project/preview_screenshot/%Y/%m/%d', verbose_name='Превью-Картинка')),
                ('header', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('slug_header', models.SlugField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Адрес сайта')),
                ('creation_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('category', models.CharField(blank=True, choices=[('sites', 'Сайты'), ('games', 'Игры'), ('software', 'Софт')], default='sites', max_length=30, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображения', upload_to='Gallery/Project/Screenshot/image/%Y/%m/%d', verbose_name='Галерея проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, verbose_name='Видео')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='project',
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
