# Generated by Django 2.0.1 on 2018-01-25 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=300, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Организация')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
            ],
        ),
    ]
